trigger:
  - main

variables:
  PUBLISH: $(PUBLISH)

# PUBLISH can be true or false, set on MFE-INTERNSHIP-PROJECT pipeline variable

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      cd event-bus
      npm install
    displayName: 'npm install'

  - script: |
      cd event-bus
      npm run build
    displayName: 'npm build'

  - script: |
      cd event-bus
      echo //registry.npmjs.org/:_authToken=$(NPM_TOKEN) > ~/.npmrc
      npm config set _authToken=$(NPM_TOKEN)
      cp package.json output
      cd output
      npm publish
    condition: eq(variables['PUBLISH'], 'true')
    displayName: 'npm publish'
